<a href="https://colab.research.google.com/github/freirefellipe/ebac/blob/develop/MOD14-resolvido.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Diamantes: preços por tipo  de corte.

In [2]:
import seaborn

In [ ]:
seaborn.get_dataset_names()

In [3]:
diamonds = seaborn.load_dataset('diamonds')

In [38]:
display(diamonds)

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [16]:
  diamonds_price_cut_ideal = diamonds[['cut', 'price']].query('cut == "Ideal"').describe().loc['mean']
  diamonds_price_cut_premium = diamonds[['cut', 'price']].query('cut == "Premium"').describe().loc['mean']
  diamonds_price_cut_good = diamonds[['cut', 'price']].query('cut == "Good"').describe().loc['mean']
  diamonds_price_cut_verygood = diamonds[['cut', 'price']].query('cut == "Very Good"').describe().loc['mean']

#.groupby('cut').agg('sum').sort_values(by='price', ascending=False)

In [14]:
display(diamonds_price_cut_verygood)

              price
count  12082.000000
mean    3981.759891
std     3935.862161
min      336.000000
25%      912.000000
50%     2648.000000
75%     5372.750000
max    18818.000000

In [ ]:
seaborn.relplot(data=diamonds_price_cut, x='cut', y='price', hue='price')